name: Notify  Slack on push

on:
  pull_request:
    branches:
      - 'main'

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

      - name: Set changed files to SLACK_MESSAGE
        run: |
          SLACK_MESSAGE=""
          for changed_file in ${{ steps.files.outputs.all }}; do
            SLACK_MESSAGE="${SLACK_MESSAGE}- ${changed_file}\n"
          done
          echo "SLACK_MESSAGE=${SLACK_MESSAGE}" >> $GITHUB_ENV
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
