name: Notify  Slack on push

on:
  pull_request:
    branches:
      - 'main'

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
        with:
          {
            'text': 'Pull Request changes:',
            'attachments':
              [
                {
                  'color': '#36a64f',
                  'title': 'Changes in settings.py',
                  'text': '$(for changed_file in ${{ steps.files.outputs.all }}; do echo "- ${changed_file}"; done)',
                },
              ],
          }
