name: Notify Slack on push
on:
  push:
    branches:
      - 'test'

jobs:
  notify_slack_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "INPUT_ARGS: $INPUT_ARGS"

      - name: Notify Slack
        uses: JayaBharatReddy-plivo/SlackNotifTest@test
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{"channel":"C0483SB96MV","text":"Repository pushed"}'
        if: success()
