name: Notify  Slack on push
on:
  push:
    branches:
      - 'test'

jobs:
  notify_slack_push:
    name: Notify Slack on pushes
    runs-on: ubuntu-latest
    steps:
      - uses: JayaBharatReddy-plivo/SlackNotifTest@test
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # message to send to slack
          args: '{\"channel\":\"C0483SB96MV\",\"text\":\"Repository pushed\"}'
        if: success()
